#!bin/bash
# Read the input acrostic from standard input
acrostic=$(cat)

# Decode the acrostic
decoded_message=""
while read -r line; do
    first_letter=$(echo "$line" | awk '{print substr($0, 1, 1)}')
    decoded_message="${decoded_message}${first_letter}"
done <<< "$acrostic"

# Print the decoded message
echo -e "${decoded_message}\n"
